import Link from "next/link";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <div className="sr_hidden">
                    <Link href="/">MCC</Link>
                </div>
                {children}
            </body>
        </html>
    );
}
